version: '3.1'

services:

  gui:
    build:
      context: gui/
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./gui:/usr/app

  api:
    build:
      context: api/
      target: dev
    ports:
      - 4000:4000
    volumes:
      - ./api:/usr/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/